package:
  name: python-softmaint
  version: "1.0.0"

source:
  path: ../../..

build:
  number: 0

about:
  home: http://statiskit.readthedocs.org
  license: Apache License 2.0
  summary: A Tool to Ease Software Maintenance

requirements:
  build:
    - python
  run:
    - python

test:
  source_files:
    - test
  requires:
    - python
  commands:
   - nosetests test -x -s -v -A "level <= {{ environ.get('TEST_LEVEL', 1) }} and linux" [linux]
   - nosetests test -x -s -v -A "level <= {{ environ.get('TEST_LEVEL', 1) }} and osx"   [osx]
   - nosetests test -x -s -v -A "level <= {{ environ.get('TEST_LEVEL', 1) }} and win"   [win]
